### ISSUE TITLE
This repo does not contain a release-4.3 branch

### ISSUE THREAD

**Issue by jupierce** [openshift/csi-external-resizer#104]
This means ART is presently building 4.3 off of the master branch.

**Comment by vfreex** [comment]
Recent 4.3 ose-csi-external-resizer builds are constantly failing, like https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=31050264.

Probably because of recent changes or golang version mismatch.

The last successful build is ose-csi-external-resizer-container-v4.3.33-202008210149.p0 using golang builder 1.12.
